server:
  port: 9999
  servlet:
    context-path: /
    session:
      timeout: 3600s     # session失效期 配置为3600秒，默认30分钟，最小1分钟


spring:
  # 数据库连接信息和数据库连接池信息
  datasource:
    url: jdbc:mysql://localhost:3306/cjr_test?serverTimezone=Asia/Shanghai
    username: root
    password: a123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # session的存储选redis（注意：session虽然存入redis，但是我之前那些session配置还是生效的）
  session:
    store-type: REDIS
  redis:
    host: localhost   # 默认就是 localhost
    port: 6379        # 默认就是 6379


# 日志配置（使用springboot默认的日志实现）
logging:
  level:
    root: info




# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper\/*.xml    # mapper.xml 文件的位置


# 下面的配置相当于 mybatis-config.xml 的配置，以后可以需要 mybatis-config.xml 了，直接使用如下配置
#mybatis-plus.type-aliases-package=com.nature.edu.entity
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.log4j2.Log4j2Impl
#mybatis-plus.configuration.call-setters-on-nulls=true
#mybatis-plus.configuration.cache-enabled=true
#mybatis-plus.configuration.map-underscore-to-camel-case=true
#mybatis-plus.global-config.db-column-underline=true
